format_version: 10
pipelines:
  mysql:
    group: expense-project
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-777c60b:
        git: https://github.com/ssrungaram2/ansible_20240306_env.git
        username: ssrungaram2
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:Mt2aEIDo4gCqrmTnr4Szng==:3tG71MyEsHrhuY1RaXBajlHAyTwKjJ26JoTyOcehI1Z284V1StlFsiOmwd9lV+0y
    stages:
    - DEV:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          ansible-playbook:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - mysql
                - dev
                command: bash
                run_if: passed

    - QA:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          ansible-playbook:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - mysql
                - qa
                command: bash
                run_if: passed

    - STAGING:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          ansible-playbook:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - mysql
                - staging
                command: bash
                run_if: passed

    - PROD:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          ansible-playbook:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - mysql
                - prod
                command: bash
                run_if: passed